/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { initiateCheckout } from "../lib/payments";

export default function Home({ products: productsData }) {
  const [showMore, setShowMore] = useState(false);
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Planet Shirt Shop</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <aside className={styles.aside}>
          <h1 className={styles.title}>Welcome to The Planet Shirt Shop</h1>
          <p className={styles.description}>
            The best planet shirts on the interwebs.
          </p>
          <div className={styles.grid}>
            <div href="https://nextjs.org/docs" className={styles.card}>
              <h2>Choose from a wide array of planets &rarr;</h2>
              <p>Nine to be exact!</p>
            </div>

            <div href="https://nextjs.org/learn" className={styles.card}>
              <h2>Choose Best fit for you</h2>
              <p>XXL is sold out though.</p>
            </div>

            <div href="https://nextjs.org/learn" className={styles.card}>
              <h2>Try the planet look</h2>
              <p>Very Powerful with the power of cosmos</p>
            </div>
            <div href="https://nextjs.org/learn" className={styles.card}>
              <h2>Black & White Variants</h2>
              <p>Come to dark side.</p>
            </div>
          </div>
        </aside>
        <main className={styles.main}>
          {productsData
            .slice(0, showMore ? productsData.length : 6)
            .map(({ name, id }) => (
              <div className={styles.imagecard} key={name}>
                <div className={styles.productImage}>
                  {" "}
                  <Image src="/tshirt-white.webp" layout="fill" alt="t shirt" />
                  <img
                    src={`/planets/${name}.svg`}
                    key={name}
                    className={styles.shirtSticker}
                    alt="planet 1"
                    height="250"
                    width="250"
                  ></img>
                </div>
                <Image
                  src={`/planets/${name}.svg`}
                  alt={`Planet ${name}`}
                  height="250"
                  width="250"
                ></Image>
                <button
                  onClick={() =>
                    initiateCheckout({
                      lineItems: [{ quantity: 1, price: id }],
                    })
                  }
                  className={styles.buyNow}
                >
                  Buy Now
                </button>
              </div>
            ))}
          <button
            onClick={() => setShowMore(!showMore)}
            passHref={true}
            className={styles.morecard}
          >
            <h3>{showMore ? "Less" : "More"} planets </h3>
          </button>
        </main>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://nextjs.org/learn"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Stripe</span>
        </a>
      </footer>
    </>
  );
}

export async function getServerSideProps(context) {
  const data = await (
    await fetch(`${process.env.HOST_URL}/api/products`)
  ).json();
  console.log(data);
  return { props: data };
}
